export const trackPlayerList = [
    {
        id: 1,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 2,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 3,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 4,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 5,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 6,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 7,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 9,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 10,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 12,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 13,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 14,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 15,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 16,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
    {
        id: 17,
        title: 'Bhalwani Gedi | Punjabi',
        url: require('./src/assets/audio/Bhalwani-Gedi.mp3'),
        artist: 'Jassa Dhillon',
        artwork: 'https://covers.djpunjab.pro/image/496732/Bhalwani-Gedi-1.jpg',
        album: 'Above All',
    },
    {
        id: 18,
        title: 'Maan Meri Jaan 2',
        url: require('./src/assets/audio/Adharam-Muharram-Vadanam.mp3'),
        artist: 'King 2',
        artwork:
            'https://c.saavncdn.com/734/Champagne-Talk-Hindi-2022-20221008011951-500x500.jpg',
        album: 'Champagne Talk',
    },
];
